content/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^mission/$', views.MissionPageView.as_view(), name='mission'),
    url(r'^winner/$', views.WinnerPageView.as_view(), name='winner'),
    url(r'^past_awards/$', views.PastAwardsPageView.as_view(),
        name='past_awards'),
]

dlpp/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from . import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('content.urls', namespace='content')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/models.py
from django.db import models


class Page(models.Model):
    title = models.CharField(max_length=255)


class Author(models.Model):
    name = models.CharField(max_length=255)
    quote = models.TextField()
    bio = models.TextField()
    image = models.ImageField()

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=255)
    summary = models.TextField()
    summary_citation = models.TextField()
    author = models.ForeignKey(Author)
    cover = models.ImageField()

    def __str__(self):
        return self.title


class AwardCategory(models.Model):
    name = models.CharField(unique=True, max_length=255)

    def __str__(self):
        return self.name


class AwardPage(models.Model):
    category = models.ForeignKey(AwardCategory)
    year = models.PositiveIntegerField()
    book = models.ForeignKey(Book)

    def __str__(self):
        return '%s - %s (%s %s)' % (self.book.title, 
            self.book.author.name, str(self.year), self.category.name)


class AdditionalAwardPageContent(models.Model):
    name = models.CharField(max_length=255)
    content = models.TextField()

    def __str__(self):
        return self.name

content/views.py
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404
from .models import Book, Author, AwardPage


class HomeView(TemplateView):
    template_name = 'content/home.html'

    def get_context_data(self, **kwargs):
        query_params = self.request.GET
        current_year_winners = AwardPage.objects.filter(year=2016)
        context = super(HomeView, self).get_context_data(**kwargs)
        context['current_year_winners'] = current_year_winners
        return context


class MissionPageView(TemplateView):
    template_name = 'content/mission.html'


class WinnerPageView(TemplateView):
    template_name = 'content/fiction_winner.html'

    def get_context_data(self, **kwargs):
        query_params = self.request.GET
        query_dict = {}
        if 'year' in query_params:
            query_dict['year'] = query_params.get('year')
        if 'author_name' in query_params:
            query_dict['book__author__name'] = query_params.get('author_name')
        if 'book_title' in query_params:
            query_dict['book__title'] = query_params.get('book_title')
        if 'category' in query_params:
            query_dict['category__name'] = query_params.get('category')
        context = super(WinnerPageView, self).get_context_data(**kwargs)
        context['page'] = get_object_or_404(AwardPage, **query_dict)
        return context


class PastAwardsPageView(TemplateView):
    template_name = 'content/past_awards.html'

    def get_context_data(self, **kwargs):
        context = super(PastAwardsPageView, self).get_context_data(**kwargs)
        years = AwardPage.objects.all().order_by('year').values_list('year', flat=True).distinct()
        awards = AwardPage.objects.all()
        context['awards'] = awards
        context['years'] = years
        return context

content/templates/content/fiction_winner.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Viet Thanh Nguyen, 2016 Fiction Winner{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6 col-lg-5 col-lg-offset-1 col-sm-12 col-md-push-6 col-lg-push-5">
            <div class="panel dark-blue-panel">
                <div class="panel-content">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="text-center">
                                    <h2>{{ page.year }} {{ page.category }}</h2>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <img class="img-responsive img-rounded center-block" src="{{ MEDIA_URL }}{{ page.book.author.image.url }}">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="text-center">
                                    <strong>{{ page.book.author.name }}<br><i>{{ page.book.title }}</i></strong>
                                </div>
                            </div>
                        </div>
                        <div class="row quote-row">
                            <div class="col-md-8 col-md-offset-2 col-xs-10 col-xs-offset-1">
                                “{{ page.book.author.quote }}”

                                <br><br><div class="pull-right">— {{ page.book.author.name }}</div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-10 col-xs-offset-1">
                                {{ page.book.author.bio }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-5 col-sm-12 col-md-pull-6 col-lg-pull-5">
            <div class="panel light-blue-panel">
                <div class="panel-content">
                    <div class="panel-body">
                        <div class="row">
                        	<div class="col-md-6 col-md-offset-3 col-sm-12">
                        	  <div class="text-center">
                                    <h3><strong><i>{{ page.book.title }}</i></strong></h3>
                                </div>
                        	</div>

                                <div class="col-md-2 col-sm-12">
                                <img class="img-responsive img-rounded center-block" src="{{ MEDIA_URL }}{{ page.book.cover.url }}">
</div>
                        </div>
                        <div class="row">
                            <div class="col-xs-10 col-xs-offset-1">
                                <p>{{ page.book.summary|linebreaks }}
                                    <br><br>
                                <div class="pull-right">
                                    {{ page.book.summary_citation|linebreaks }}
                                </div>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

content/templates/content/mission.html
{% extends 'base.html' %}
{% load static %}

{% block script %}
<script type="text/javascript">
$(document).ready(function () {
    $('#nav-mission').addClass('active');
})
</script>
{% endblock %}

{% block title %}Mission{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-10 col-lg-offset-1 col-sm-12">
            <div class="panel dark-blue-panel">
                <div class="panel-content">
                    <div class="row">
                        <div class="col-sm-12">
                            <h2 class="text-center">The Mission of the Dayton Literary Peace Prize</h2>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-10 col-xs-offset-1">
                            <img class="img-responsive" src="{% static 'img/Award-140x370-blue.jpg' %}" width="140" height="370" style="float: right">
                            <p>The Dayton Literary Peace Prize Foundation (DLPP) was established to advance peace through literature. We support those who write, publish, read and share works of fiction and nonfiction that promote peace and understanding.
                                <br>
                                Our goals are:</p>
                            <ul>
                                <li>To promote peace by encouraging people to read, share, and appreciate literary works about peace,</li>
                                <li>To promote the recognition of literature as a force in achieving peace, and </li>
                                <li>To establish prizes to recognize writers and the role their books play in educating people about peace.</li>
                            </ul>
                            <p>
                                <strong>Award Criteria</strong>
                                <br>
                                <ul>
                            <li>Nominated works should focus on peace: increasing understanding between and among people as individuals or within and between families, communities, nations, ethnic groups, cultures and religions. Works should have enduring literary value and should appeal to a variety of audiences.
                                <ul>
                                    <li>ending or seeking to end conflict—personal, national or international, </li>
                                    <li>establishing concord between and among people, or</li>
                                    <li>showing consequences of persons, nations or institutions recklessly disrupting personal harmony or universal accord. </li>
                                </ul>
                            </li>
                        </ul>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

content/templates/content/past_awards.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Past Awards{% endblock %}

{% block style %}
<style>
    #past-awards-nav .active > a {
        background-color: #eeeeee;
        color: #234F6E;
    }

    li.dropdown .dropdown-menu {
        width: 100%;
    }

    #results-panel {
        margin-top: 20px;
    }
</style>
{% endblock %}

{% block script %}
<script type="text/javascript">
$(document).ready(function () {
    $('#nav-past-awards').addClass('active');

    $('.display-by-link').on('click', function (e) {
        e.preventDefault();
        $('.display-by-link').removeClass('active');
        $(this).addClass('active');
        if ($(this).data('toggle') === 'author') {
            $('.img-book').fadeOut(function () {
                $('.img-author').fadeIn();
            });
            $('.author-header').each(function () {
                $(this).replaceWith('<h5 class="author-header dark-blue-text">' + this.innerHTML + '</h5>');
            });
            $('.book-header').each(function () {
                var html = this.innerHTML;
                var authorHeader = $(this).parent().find('.author-header');
                $(this).remove();
                authorHeader.after('<h6 class="book-header dark-blue-text">' + this.innerHTML + '</h6>');
            });
        } else if ($(this).data('toggle') === 'book') {
            $('.img-author').fadeOut(function () {
                $('.img-book').fadeIn();
            });
            $('.book-header').each(function () {
                $(this).replaceWith('<h5 class="book-header dark-blue-text">' + this.innerHTML + '</h5>');
            });
            $('.author-header').each(function () {
                var html = this.innerHTML;
                var bookHeader = $(this).parent().find('.book-header');
                $(this).remove();
                bookHeader.after('<h6 class="author-header dark-blue-text">' + this.innerHTML + '</h6>');
            });
        }
    });
});
</script>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-10 col-lg-offset-1 col-sm-12">
            <div class="panel dark-blue-panel">
                <div class="panel-content">
                    <div class="row">
                        <div class="col-sm-12">
                            <h2 class="text-center">Past Awards</h2>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-10 col-xs-offset-1">
                            <ul class="nav nav-pills nav-justified" id="past-awards-nav">
                                <li role="presentation" class="dropdown">
                                    <a class="dropdown-toggle white-text" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                                    <span class="glyphicon glyphicon-th-large"></span> Categories <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#">Holbrooke Award</a></li>
                                        <li><a href="#">Fiction Winner</a></li>
                                        <li><a href="#">Fiction Runner-up</a></li>
                                        <li><a href="#">Nonfiction Winner</a></li>
                                        <li><a href="#">Nonfiction Runner-up</a></li>
                                        <li role="separator" class="divider"></li>                                        
                                        <li><a href="#">Finalists</a></li>
                                        <li><a href="#">Finalist Judges</a></li>
                                        <li><a href="#">Sponsors</a></li>
                                        <li><a href="#">Master of Ceremonies</a></li>
                                    </ul>
                                </li>
                                <li role="presentation" class="dropdown">
                                    <a class="dropdown-toggle white-text" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                                    <span class="glyphicon glyphicon-calendar"></span> Years <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        {% for year in years %}
                                            <li><a href="#">{{ year }}</a></li>
                                        {% endfor %}
                                    </ul>
                                </li>
                                <li role="presentation" class="dropdown">
                                    <a class="dropdown-toggle white-text" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                                    <span class="glyphicon glyphicon-th-list"></span> Display By <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                    <li class="active display-by-link" data-toggle="author"><a href="#"><span class="glyphicon glyphicon-user"></span> Author</a></li>
                                    <li class="display-by-link" data-toggle="book" ><a href="#"><span class="glyphicon glyphicon-book"></span> Book</a></li>
                                    </ul>
                                </li>
                            </ul>
                            <div class="panel light-blue-panel" id="results-panel">
                                <div class="panel-content">
                                    <div class="panel-body">
                                        {% for award in awards %}
                                            <div class="col-md-4 col-sm-6 col-xs-12">
                                                <div class="well">
                                                    <a href="{% url 'content:winner' %}?author_name={{ award.book.author.name }}&book_title={{ award.book.title }}">
                                                        <img class="img-responsive img-rounded img-author" src="{{ MEDIA_URL }}{{ award.book.author.image.url }}">
                                                        <img class="img-responsive img-rounded img-book" src="{{ MEDIA_URL }}{{ award.book.cover.url }}" style="display: none">
                                                        <h5 class="author-header dark-blue-text">{{ award.book.author.name }}</h5>
                                                        <h6 class="book-header dark-blue-text"><i>{{ award.book.title }}</i></h6>
                                                    </a>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %} | Dayton Literary Peace Prize</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Courgette" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block style %}
    {% endblock %}

    <script src="http://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/base.js' %}"></script>
    {% block script %}
    {% endblock %}
</head>
<body>
<div class="jumbotron" id="dlpp-jumbotron">
    <div class="row">
        <div class="col-sm-12">
            <a href="{% url 'content:home' %}"><img class="img-responsive" src="{% static 'img/DLPP_Logo-468x324-transpare.png' %}" width="234" height="162" style="float:left"></img></a>
            <p class="visible-md visible-lg">The first and only annual U.S. literary award recognizing the power of the written word to promote peace.</p>
        </div>
    </div>
    <div class="row visible-xs visible-sm">
        <div class="col-xs-12">
            <p>The first and only annual U.S. literary award recognizing the power of the written word to promote peace.</p>
        </div>
    </div>
</div>
<nav class="navbar" id="dlpp-navbar">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li id="nav-home"><a href="{% url 'content:home' %}">Home</a></li>
                <li id="nav-mission"><a href="{% url 'content:mission' %}">Mission</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">2016 Awards <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'content:winner' %}?year=2016&category=Holbrooke Award">Holbrooke Award</a></li>
                        <li><a href="{% url 'content:winner' %}?year=2016&category=Fiction Winner">Fiction Winner</a></li>
                        <li><a href="{% url 'content:winner' %}?year=2016&category=Fiction Runner-up">Fiction Runner-up</a></li>
                        <li><a href="{% url 'content:winner' %}?year=2016&category=Nonfiction Winner">Nonfiction Winner</a></li>
                        <li><a href="{% url 'content:winner' %}?year=2016&category=Nonfiction Runner-up">Nonfiction Runner-up</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Finalists</a></li>
                        <li><a href="#">Finalist Judges</a></li>
                        <li><a href="#">Sponsors</a></li>
                    </ul>
                </li>
        	<li id="nav-past-awards"><a href="{% url 'content:past_awards' %}">Past Awards</a></li>
            </ul>
          <form class="navbar-form navbar-right" role="search">
  <div class="form-group">
<div class="input-group">
      <span class="input-group-btn">
        <button class="btn btn-default" type="button"><span class="glyphicon glyphicon-search"></span></button>
      </span>
      <input type="text" class="form-control" placeholder="Search">
    </div>
</form>
        </div>

    </div>
</nav>
<div class="container-fluid">
    {% block content %}

    {% endblock %}
</div>
</body>
</html>